"use strict";
var runtime;
(function (runtime) {
    runtime.online = { user: { id: '' } };
    runtime.player = runtime.online.user;
    runtime.reason = '';
    runtime.barkeep = { user: { id: '_BAR' } };
    runtime.dwarf = { user: { id: '_DM' } };
    runtime.neptune = { user: { id: '_NEP' } };
    runtime.seahag = { user: { id: '_OLD' } };
    runtime.taxman = { user: { id: '_TAX' } };
    runtime.witch = { user: { id: '_WOW' } };
    runtime.king = { id: '' };
    runtime.sysop = { id: '_SYS' };
    runtime.arena = 0;
    runtime.argue = 0;
    runtime.bail = 0;
    runtime.brawl = 0;
    runtime.dungeon = 0;
    runtime.joust = 0;
    runtime.jumped = 0;
    runtime.naval = 0;
    runtime.party = 0;
    runtime.realestate = 0;
    runtime.rob = 0;
    runtime.security = 0;
    runtime.sorceress = 0;
    runtime.steal = 0;
    runtime.taxboss = 0;
    runtime.tiny = 0;
    runtime.timeleft = 0;
    runtime.warning = 2;
    runtime.border = false;
    runtime.callers = [];
    runtime.remote = process.env.REMOTEHOST || process.env.SSH_CLIENT || '';
})(runtime || (runtime = {}));
module.exports = runtime;
